
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        {children}

        <footer>
          <p>Product images that are used in this website not are under my property. I only use them to create an academic project and do not benefit from it.</p>
        </footer>
        </body>
    </html>
  )
}
